# Generated by Django 4.2.6 on 2023-10-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('ChapterReveal', models.TextField()),
                ('EpisodeReveal', models.TextField()),
                ('YearReveal', models.TextField()),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='database_search',
        ),
    ]
