# Generated by Django 4.2.6 on 2023-10-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0003_rename_chapterreveal_characters_chapter_reveal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='chapter_reveal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='episode_reveal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='year_reveal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
